version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome

  gorani:
    image: ndaemy/gorani:0.1.0
    depends_on:
      - selenium
    links:
      - selenium
    ports:
      - 3000:3000
